// src/config/texts.js

export const texts = {
  en: {
    title: "IQ180",
    welcome: "Welcome",
    subtitle: "Challenge your logic to the limit.",
    enterName: "Enter nickname...",
    start: "Start",
    selectMode: "Select Game Mode",
    easy: "Normal Mode",
    hard: "Genius Mode",
    target: "Target",
    timeLeft: "Time Left",
    score: "Score",
    delete: "Delete",
    submit: "Submit",
    correct: "✅ Correct!",
    wrong: "❌ Wrong!",
    timeout: "⏰ Time’s Up!",
    playAgain: "Play Again",
    exit: "Exit",
    back: "Back",
    stats: "Stats Summary",
    history: "History",
    rounds: "Rounds Played",
    notEnough: "Use all digits before submitting!",
    invalidExpr: "Invalid Expression. Each number must be followed by an operator.",
    buildEq: "Build your equation...",
    playerName: "Player Name",
    solution: "Possible Solution",
  },

  th: {
    title: "IQ180",
    welcome: "ยินดีต้อนรับ",
    subtitle: "ท้าทายตรรกะของคุณให้ถึงขีดสุด!",
    enterName: "กรอกชื่อผู้เล่น...",
    start: "เริ่ม",
    selectMode: "เลือกโหมดเกม",
    easy: "โหมดปกติ",
    hard: "โหมดอัจฉริยะ",
    target: "เป้าหมาย",
    timeLeft: "เวลาที่เหลือ",
    score: "คะแนน",
    delete: "ลบ",
    submit: "ตรวจคำตอบ",
    correct: "✅ ถูกต้อง!",
    wrong: "❌ ผิด!",
    timeout: "⏰ หมดเวลา!",
    playAgain: "เล่นต่อ",
    exit: "ออกจากเกม",
    back: "ย้อนกลับ",
    stats: "สรุปผลการเล่น",
    history: "ประวัติการเล่น",
    rounds: "จำนวนรอบทั้งหมด",
    notEnough: "ต้องใช้เลขทั้งหมดก่อนกดส่งคำตอบ!",
    invalidExpr: "รูปแบบสมการไม่ถูกต้อง ต้องมีเครื่องหมายคั่นระหว่างเลข",
    buildEq: "สร้างสมการของคุณ...",
    playerName: "ชื่อผู้เล่น",
    solution: "วิธีเฉลยที่เป็นไปได้",
  },

  zh: {
    title: "IQ180",
    welcome: "欢迎",
    subtitle: "挑战你的逻辑极限！",
    enterName: "输入昵称...",
    start: "开始",
    selectMode: "选择模式",
    easy: "普通模式",
    hard: "天才模式",
    target: "目标",
    timeLeft: "剩余时间",
    score: "分数",
    delete: "删除",
    submit: "提交",
    correct: "✅ 正确!",
    wrong: "❌ 错误!",
    timeout: "⏰ 时间到!",
    playAgain: "再玩一次",
    exit: "退出游戏",
    back: "返回",
    stats: "统计结果",
    history: "历史记录",
    rounds: "游戏轮次",
    notEnough: "请使用所有数字再提交！",
    invalidExpr: "表达式无效，数字之间必须有运算符。",
    buildEq: "建立你的方程式...",
    playerName: "玩家名称",
    solution: "可能的解法",
  },
};

/**
 * Get translation table for a language.
 * Fallback to English if unsupported.
 * @param {string} lang - language code ('en', 'th', 'zh')
 */
export function getTexts(lang = "en") {
  return texts[lang] || texts.en;
}
